### ISSUE TITLE
Drupal links use port 8080 at times

### ISSUE THREAD

**Issue by nigelkirby** [jmizell/Drupal-CiviCRM#6]
I noticed that some assets and AJAX calls within the dashboard are linked as localhost:8080, which then fail. I ran the container again, mapping port 80 to 8080 and it all looks good. I didn't do any digging to see why it was linking to 8080 in places, some Drupal thing I would guess. Changing the documentation to run these with `-p 8080:80` would of course prevent people from experiencing this but maybe isn't what you want.

Thanks a lot for putting this together, it was really helpful for me.

**Comment by jmizell** [comment]
Ultimately the goal was to make this production ready, and support http, and https, meaning port 8080 wouldn't be ideal. I had noticed the port 8080 issue, but the app appeared to work well enough for testing purposes, so I didn't pursue it immediately 

After spending some time trying configure CiviCRM, I've decided that for the project I had in mind, it requires too much effort to configure, and it doesn't have the ease of use necessary for bringing in non-technical volunteers.
